# Generated by Django 4.1 on 2023-02-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Addproduct',
            fields=[
                ('prodid', models.AutoField(primary_key=True, serialize=False)),
                ('prodname', models.CharField(max_length=100)),
                ('prodcategory', models.CharField(choices=[('shoes', 'shoes'), ('clothes', 'clothes'), ('electronics', 'electronics'), ('food', 'food'), ('handmade', 'handmade')], max_length=100)),
                ('prodimage', models.ImageField(upload_to='images')),
                ('prodprice', models.CharField(default=0, max_length=100)),
                ('prodabout', models.CharField(max_length=100)),
                ('produser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localapi.registeruser')),
            ],
        ),
    ]
