# Generated by Django 4.1 on 2023-02-12 15:45

from django.db import migrations, models
import localapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('localapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='prodimage',
            field=models.ImageField(blank=True, null=True, upload_to=localapi.models.upload_to),
        ),
    ]
