# Generated by Django 4.1 on 2023-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localapi', '0004_alter_registeruser_isseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='registertime',
            field=models.DateField(auto_now=True),
        ),
    ]
